import * as swissnode from '../';

swissnode.ask;
swissnode.ask.text;
swissnode.ask.autotext;
swissnode.ask.number;
swissnode.ask.boolean;
swissnode.ask.booleanAlt;
swissnode.ask.select;
swissnode.ask.multiselect;
swissnode.ask.crud;
swissnode.ask.validate;
swissnode.ask.imitate;
swissnode.ask.prefill;
swissnode.ask.loading;
swissnode.ask.pause;
swissnode.ask.countdown;
swissnode.ask.wizard;
swissnode.ask.date;
swissnode.ask.time;
swissnode.ask.datetime;
swissnode.ask.dateRange;
swissnode.ask.fileExplorer;
swissnode.ask.multiFileExplorer;
swissnode.ask.saveFileExplorer;
swissnode.ask.table;
swissnode.ask.table.select;
swissnode.ask.table.multiselect;
swissnode.ask.trim;
swissnode.ask.separator;
swissnode.ask.section;
swissnode.ask.utils;
swissnode.ask.utils.itemsToPromptObjects;

swissnode.out;
swissnode.out.pad;
swissnode.out.center;
swissnode.out.left;
swissnode.out.right;
swissnode.out.justify;
swissnode.out.leftLines;
swissnode.out.centerLines;
swissnode.out.rightLines;
swissnode.out.justifyLines;
swissnode.out.align;
swissnode.out.split;
swissnode.out.wrap;
swissnode.out.moveUp;
swissnode.out.loading;
swissnode.out.limitToLength;
swissnode.out.limitToLengthStart;
swissnode.out.truncate;
swissnode.out.truncateStart;
swissnode.out.concatLineGroups;
swissnode.out.getResponsiveValue;
type outResponsiveOption = swissnode.out.ResponsiveOption<number>;
swissnode.out.getBreadcrumb;
swissnode.getBreadcrumb;
type outBreadcrumb = swissnode.out.Breadcrumb;
type Breadcrumb = swissnode.Breadcrumb;
swissnode.out.getLineCounter;
swissnode.getLineCounter;
type outLineCounter = swissnode.out.LineCounter;
type LineCounter = swissnode.LineCounter;
swissnode.out.utils;
swissnode.out.utils.getTerminalWidth;
swissnode.out.utils.getLines;
swissnode.out.utils.getNumLines;
swissnode.out.utils.getLinesWidth;
swissnode.out.utils.getLogLines;
swissnode.out.utils.getNumLogLines;
swissnode.out.utils.getLogLinesWidth;
swissnode.out.utils.joinLines;
swissnode.out.utils.hasColor;

swissnode.chlk;
swissnode.chlk.gray0;
swissnode.chlk.gray1;
swissnode.chlk.gray2;
swissnode.chlk.gray3;
swissnode.chlk.gray4;
swissnode.chlk.gray5;
swissnode.chlk.grays;
swissnode.chlk.gray;
swissnode.chlk.clear;
swissnode.chlk.not;
swissnode.chlk.notUnderlined;
swissnode.clr;
swissnode.clr.gray0;
swissnode.clr.gray1;
swissnode.clr.gray2;
swissnode.clr.gray3;
swissnode.clr.gray4;
swissnode.clr.gray5;
swissnode.clr.hl1;
swissnode.clr.hl2;
swissnode.clr.approve;
swissnode.clr.create;
swissnode.clr.update;
swissnode.clr.remove;
swissnode.clr.removeAll;
swissnode.clr.blue;
swissnode.clr.cyan;
swissnode.clr.green;
swissnode.clr.magenta;
swissnode.clr.red;
swissnode.clr.yellow;
swissnode.clr.t1;
swissnode.clr.t2;
swissnode.clr.t3;
swissnode.clr.t4;
swissnode.clr.t5;
swissnode.clr.t6;

swissnode.table;
swissnode.table.print;
swissnode.table.printObjects;
swissnode.table.markdown;
swissnode.table.getLines;
swissnode.table.utils;
swissnode.table.utils.objectsToTable;
swissnode.table.utils.transpose;
swissnode.table.utils.concatRows;
swissnode.table.utils.getFormat;

swissnode.log;
swissnode.createLogger;
type LogOptions = swissnode.LogOptions;
type LogConfig = swissnode.LogConfig;

swissnode.LogTools;
swissnode.LogTools.getLogStr;
swissnode.getLogStr;
swissnode.LogTools.processLogContents;
swissnode.processLogContents;
swissnode.LogTools.getLog;
swissnode.getLog;

swissnode.PathTools;
swissnode.PathTools.explodePath;
swissnode.explodePath;
type PathToolsExplodedPath = swissnode.PathTools.ExplodedPath;
type ExplodedPath = swissnode.ExplodedPath;
swissnode.PathTools.removeTrailSlash;
swissnode.PathTools.trailSlash;
swissnode.PathTools.removeDoubleSlashes;

swissnode.progressBarTools;
swissnode.progressBarTools.getColouredProgressBarOpts;

swissnode.nextTick;
swissnode.waiters.nextTick;

// --------------------------- PROGRESS LINE ---------------------------

swissnode.getKeyListener;
type KeyListener = swissnode.KeyListener;
